using HyperPayIntegration.EntityFrameworkCore;
using Xunit;

namespace HyperPayIntegration.EntityFrameworkCore;

public class HyperPayIntegrationEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<HyperPayIntegrationEntityFrameworkCoreFixture>
{

}
